name: Auto Generate and Replace Reference Files

on: [push]

jobs:
  generate_reference-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew
      - name: List Gradle task
        run: ./gradlew dokkaHtml
      - name: zip docs
        run: zip -r docs.zip docs/
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs.zip
